development:
  bucket: mexilist-dev
  access_key_id: AKIAJN5UWEKNER3LIOHA
  secret_access_key: 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
production:
  bucket: mexilist-pro
  access_key_id: AKIAJN5UWEKNER3LIOHA
  secret_access_key: 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