# -*- coding: ascii-8bit -*-
State.create_or_update([
                        { :id => 1, :name => 'Distrito Federal'},
                        { :id => 2, :name => 'Estado de México'},
                        { :id => 9, :name => 'Jalisco'}
                       ])

City.create_or_update([
                        { :id => 11, :name => 'Álvaro Obregón', :state_id => 1, :metropoly_id => 1},
                        { :id => 12, :name => 'Coyoacán', :state_id => 1, :metropoly_id => 1},
                        { :id => 13, :name => 'Azcapotzalco', :state_id => 1, :metropoly_id => 1},
                        { :id => 14, :name => 'Benito Juárez', :state_id => 1, :metropoly_id => 1},
                        { :id => 15, :name => 'Cuajimalpa', :state_id => 1, :metropoly_id => 1},
                        { :id => 16, :name => 'Iztacalco', :state_id => 1, :metropoly_id => 1},
                        { :id => 113, :name => 'Cuauhtémoc', :state_id => 1, :metropoly_id => 1},
                        { :id => 114, :name => 'Gustavo A. Madero', :state_id => 1, :metropoly_id => 1},
                        { :id => 115, :name => 'Iztapalapa', :state_id => 1, :metropoly_id => 1},
                        { :id => 17, :name => 'Milpa Alta', :state_id => 1, :metropoly_id => 1},
                        { :id => 18, :name => 'Magdalena Contreras', :state_id => 1, :metropoly_id => 1},
                        { :id => 19, :name => 'Miguel Hidalgo', :state_id => 1, :metropoly_id => 1},
                        { :id => 110, :name => 'Tlalpan', :state_id => 1, :metropoly_id => 1},
                        { :id => 111, :name => 'Xochimilco', :state_id => 1, :metropoly_id => 1},
                        { :id => 112, :name => 'Tláhuac', :state_id => 1, :metropoly_id => 1},
                        { :id => 116, :name => 'Venustiano Carranza', :state_id => 1, :metropoly_id => 1},


                        { :id => 21, :name => 'Acolman', :state_id => 2, :metropoly_id => 1},
                        { :id => 22, :name => 'Amecameca', :state_id => 2, :metropoly_id => 1},
                        { :id => 23, :name => 'Apaxco', :state_id => 2, :metropoly_id => 1},
                        { :id => 24, :name => 'Atenco', :state_id => 2, :metropoly_id => 1},
                        { :id => 25, :name => 'Atizapán de Zaragoza', :state_id => 2, :metropoly_id => 1},
                        { :id => 26, :name => 'Atlautla', :state_id => 2, :metropoly_id => 1},
                        { :id => 27, :name => 'Axapusco', :state_id => 2, :metropoly_id => 1},
                        { :id => 28, :name => 'Ayapango', :state_id => 2, :metropoly_id => 1},
                        { :id => 29, :name => 'Coacalco de Berriozábal', :state_id => 2, :metropoly_id => 1},
                        { :id => 210, :name => 'Cocotitlán', :state_id => 2, :metropoly_id => 1},
                        { :id => 211, :name => 'Coyotepec', :state_id => 2, :metropoly_id => 1},
                        { :id => 212, :name => 'Cuautitlán', :state_id => 2, :metropoly_id => 1},
                        { :id => 213, :name => 'Chalco', :state_id => 2, :metropoly_id => 1},
                        { :id => 214, :name => 'Chiautla', :state_id => 2, :metropoly_id => 1},
                        { :id => 215, :name => 'Chicoloapan', :state_id => 2, :metropoly_id => 1},
                        { :id => 216, :name => 'Chiconcuac', :state_id => 2, :metropoly_id => 1},
                        { :id => 217, :name => 'Chimalhuacán', :state_id => 2, :metropoly_id => 1},
                        { :id => 218, :name => 'Ecatepec de Morelos', :state_id => 2, :metropoly_id => 1},
                        { :id => 219, :name => 'Ecatzingo', :state_id => 2, :metropoly_id => 1},
                        { :id => 220, :name => 'Huehuetoca', :state_id => 2, :metropoly_id => 1},
                        { :id => 221, :name => 'Hueypoxtla', :state_id => 2, :metropoly_id => 1},
                        { :id => 222, :name => 'huixquilucan', :state_id => 2, :metropoly_id => 1},
                        { :id => 223, :name => 'Isidro Fabela', :state_id => 2, :metropoly_id => 1},
                        { :id => 224, :name => 'Ixtapaluca', :state_id => 2, :metropoly_id => 1},
                        { :id => 225, :name => 'Jaltenco', :state_id => 2, :metropoly_id => 1},
                        { :id => 226, :name => 'Jilotzingo', :state_id => 2, :metropoly_id => 1},
                        { :id => 227, :name => 'Juchitepec', :state_id => 2, :metropoly_id => 1},
                        { :id => 228, :name => 'Melchor Ocampo', :state_id => 2, :metropoly_id => 1},
                        { :id => 229, :name => 'Naucalpan de Juárez', :state_id => 2, :metropoly_id => 1},
                        { :id => 230, :name => 'Nezahualcóyotl', :state_id => 2, :metropoly_id => 1},
                        { :id => 231, :name => 'Nextlalpan', :state_id => 2, :metropoly_id => 1},
                        { :id => 232, :name => 'Nicolás Romero', :state_id => 2, :metropoly_id => 1},
                        { :id => 233, :name => 'Nopaltepec', :state_id => 2, :metropoly_id => 1},
                        { :id => 234, :name => 'Otumba', :state_id => 2, :metropoly_id => 1},
                        { :id => 235, :name => 'Ozumba', :state_id => 2, :metropoly_id => 1},
                        { :id => 236, :name => 'Papalotla', :state_id => 2, :metropoly_id => 1},
                        { :id => 237, :name => 'La Paz', :state_id => 2, :metropoly_id => 1},
                        { :id => 238, :name => 'San Martín de las Pirámides', :state_id => 2, :metropoly_id => 1},
                        { :id => 239, :name => 'Tecámac', :state_id => 2, :metropoly_id => 1},
                        { :id => 240, :name => 'Temamatla', :state_id => 2, :metropoly_id => 1},
                        { :id => 241, :name => 'Temascalapa', :state_id => 2, :metropoly_id => 1},
                        { :id => 242, :name => 'Tenango del Aire', :state_id => 2, :metropoly_id => 1},
                        { :id => 243, :name => 'Teoloyucán', :state_id => 2, :metropoly_id => 1},
                        { :id => 244, :name => 'Teotihuacán', :state_id => 2, :metropoly_id => 1},
                        { :id => 245, :name => 'Tepetlaoxtoc', :state_id => 2, :metropoly_id => 1},
                        { :id => 246, :name => 'Tepetlixpa', :state_id => 2, :metropoly_id => 1},
                        { :id => 247, :name => 'Tepotzotlán', :state_id => 2, :metropoly_id => 1},
                        { :id => 248, :name => 'Tequixquiac', :state_id => 2, :metropoly_id => 1},
                        { :id => 249, :name => 'Texcoco', :state_id => 2, :metropoly_id => 1},
                        { :id => 250, :name => 'Tezoyuca', :state_id => 2, :metropoly_id => 1},
                        { :id => 251, :name => 'Tlalmanalco', :state_id => 2, :metropoly_id => 1},
                        { :id => 252, :name => 'Tlalnepantla de Baz', :state_id => 2, :metropoly_id => 1},
                        { :id => 253, :name => 'Tultepec', :state_id => 2, :metropoly_id => 1},
                        { :id => 254, :name => 'Tultitlán', :state_id => 2, :metropoly_id => 1},
                        { :id => 255, :name => 'Villa del Carbón', :state_id => 2, :metropoly_id => 1},
                        { :id => 256, :name => 'Zumpango', :state_id => 2, :metropoly_id => 1},
                        { :id => 257, :name => 'Cuautitlán Izcalli', :state_id => 2, :metropoly_id => 1},
                        { :id => 258, :name => 'Valle de Chalco Solidaridad', :state_id => 2, :metropoly_id => 1},
                        { :id => 259, :name => 'Tonanitla', :state_id => 2, :metropoly_id => 1},


                        { :id => 91, :name => 'Guadalajara', :state_id => 9, :metropoly_id => 2},
                        { :id => 92, :name => 'Zapopan', :state_id => 9, :metropoly_id => 2},
                        { :id => 93, :name => 'Tlaquepaque', :state_id => 9, :metropoly_id => 2},
                        { :id => 94, :name => 'Tonalá', :state_id => 9, :metropoly_id => 2},
                        { :id => 95, :name => 'Tlajomulco de Zuñiga', :state_id => 9, :metropoly_id => 2},
                        { :id => 96, :name => 'El Salto', :state_id => 9, :metropoly_id => 2},
                        { :id => 97, :name => 'Ixtlahuacán de los Membrillos', :state_id => 9, :metropoly_id => 2},
                        { :id => 98, :name => 'Juanacatlán', :state_id => 9, :metropoly_id => 2}
                       ])

Metropoly.create_or_update([
                            { :id => 1, :name => 'Ciudad de México'},
                            { :id => 2, :name => 'Guadalajara'},
                           ])
