# -*- coding: utf-8 -*-
Model.create_or_update([
                        { :id => 1, :brand_id => 1, :name => 'CL', :tipo => 1},
                        { :id => 2, :brand_id => 1, :name => 'MDX', :tipo => 4},
                        { :id => 3, :brand_id => 1, :name => 'RDX', :tipo => 4},
                        { :id => 4, :brand_id => 1, :name => 'RL', :tipo => 1},
                        { :id => 5, :brand_id => 1, :name => 'TL', :tipo => 1},
                        { :id => 6, :brand_id => 1, :name => 'TSX', :tipo => 1},
                        { :id => 7, :brand_id => 2, :name => '147', :tipo => 1},
                        { :id => 8, :brand_id => 2, :name => '156', :tipo => 1},
                        { :id => 9, :brand_id => 2, :name => '159', :tipo => 1},
                        { :id => 10, :brand_id => 2, :name => 'Brera', :tipo => 1},
                        { :id => 11, :brand_id => 2, :name => 'GT', :tipo => 1},
                        { :id => 12, :brand_id => 2, :name => 'Spider', :tipo => 1},
                        { :id => 13, :brand_id => 3, :name => 'DB9', :tipo => 1},
                        { :id => 14, :brand_id => 3, :name => 'DBS', :tipo => 1},
                        { :id => 15, :brand_id => 3, :name => 'Vanquish', :tipo => 1},
                        { :id => 16, :brand_id => 3, :name => 'Vantage', :tipo => 1},
                        { :id => 17, :brand_id => 4, :name => 'A3', :tipo => 1},
                        { :id => 18, :brand_id => 4, :name => 'A4', :tipo => 1},
                        { :id => 19, :brand_id => 4, :name => 'A5', :tipo => 1},
                        { :id => 20, :brand_id => 4, :name => 'A6', :tipo => 1},
                        { :id => 21, :brand_id => 4, :name => 'A8', :tipo => 1},
                        { :id => 22, :brand_id => 4, :name => 'Allroad', :tipo => 1},
                        { :id => 23, :brand_id => 4, :name => 'Q7', :tipo => 4},
                        { :id => 24, :brand_id => 4, :name => 'R8', :tipo => 1},
                        { :id => 25, :brand_id => 4, :name => 'RS4', :tipo => 1},
                        { :id => 26, :brand_id => 4, :name => 'RS6', :tipo => 1},
                        { :id => 27, :brand_id => 4, :name => 'S3', :tipo => 1},
                        { :id => 28, :brand_id => 4, :name => 'S4', :tipo => 1},
                        { :id => 29, :brand_id => 4, :name => 'S5', :tipo => 1},
                        { :id => 30, :brand_id => 4, :name => 'S6', :tipo => 1},
                        { :id => 31, :brand_id => 4, :name => 'S8', :tipo => 1},
                        { :id => 32, :brand_id => 4, :name => 'TT', :tipo => 1},
                        { :id => 33, :brand_id => 5, :name => 'Arnage', :tipo => 1},
                        { :id => 34, :brand_id => 6, :name => 'Serie 1', :tipo => 1},
                        { :id => 35, :brand_id => 6, :name => 'Serie 3', :tipo => 1},
                        { :id => 36, :brand_id => 6, :name => 'Serie 5', :tipo => 1},
                        { :id => 37, :brand_id => 6, :name => 'Serie 6', :tipo => 1},
                        { :id => 38, :brand_id => 6, :name => 'Serie 7', :tipo => 1},
                        { :id => 39, :brand_id => 6, :name => 'Serie 8', :tipo => 1},
                        { :id => 40, :brand_id => 6, :name => 'X3', :tipo => 4},
                        { :id => 41, :brand_id => 6, :name => 'X5', :tipo => 4},
                        { :id => 42, :brand_id => 6, :name => 'X6', :tipo => 4},
                        { :id => 43, :brand_id => 6, :name => 'Z3', :tipo => 1},
                        { :id => 44, :brand_id => 6, :name => 'Z4', :tipo => 1},
                        { :id => 45, :brand_id => 6, :name => 'Z8', :tipo => 1},
                        { :id => 46, :brand_id => 7, :name => 'Century', :tipo => 1},
                        { :id => 47, :brand_id => 7, :name => 'LeSabre', :tipo => 1},
                        { :id => 48, :brand_id => 7, :name => 'Regal', :tipo => 1},
                        { :id => 49, :brand_id => 7, :name => 'Rivera', :tipo => 1},
                        { :id => 50, :brand_id => 8, :name => 'BLS', :tipo => 1},
                        { :id => 51, :brand_id => 8, :name => 'Catera', :tipo => 1},
                        { :id => 52, :brand_id => 8, :name => 'CTS', :tipo => 1},
                        { :id => 53, :brand_id => 8, :name => 'DeVille', :tipo => 1},
                        { :id => 54, :brand_id => 8, :name => 'Eldorado', :tipo => 1},
                        { :id => 55, :brand_id => 8, :name => 'Escalade', :tipo => 4},
                        { :id => 56, :brand_id => 8, :name => 'ESV', :tipo => 4},
                        { :id => 57, :brand_id => 8, :name => 'EXT', :tipo => 2},
                        { :id => 58, :brand_id => 8, :name => 'Seville', :tipo => 1},
                        { :id => 59, :brand_id => 8, :name => 'SLS', :tipo => 1},
                        { :id => 60, :brand_id => 8, :name => 'SRX', :tipo => 4},
                        { :id => 61, :brand_id => 8, :name => 'STS', :tipo => 1},
                        { :id => 62, :brand_id => 8, :name => 'XLR', :tipo => 1},
                        { :id => 63, :brand_id => 9, :name => 'Astra', :tipo => 1},
                        { :id => 64, :brand_id => 9, :name => 'Astro', :tipo => 4},
                        { :id => 65, :brand_id => 9, :name => 'Avalanche', :tipo => 2},
                        { :id => 66, :brand_id => 9, :name => 'Aveo', :tipo => 1},
                        { :id => 67, :brand_id => 9, :name => 'Bel Air', :tipo => 1},
                        { :id => 68, :brand_id => 9, :name => 'Blazer', :tipo => 4},
                        { :id => 69, :brand_id => 9, :name => 'C30', :tipo => 16},
                        { :id => 70, :brand_id => 9, :name => 'Camaro', :tipo => 1},
                        { :id => 71, :brand_id => 9, :name => 'Caprice', :tipo => 1},
                        { :id => 72, :brand_id => 9, :name => 'Captiva', :tipo => 4},
                        { :id => 73, :brand_id => 9, :name => 'Cavalier', :tipo => 1},
                        { :id => 74, :brand_id => 9, :name => 'Celebrity', :tipo => 1},
                        { :id => 75, :brand_id => 9, :name => 'Chevy', :tipo => 1},
                        { :id => 76, :brand_id => 9, :name => 'Cheyenne', :tipo => 2},
                        { :id => 77, :brand_id => 9, :name => 'Colorado', :tipo => 2},
                        { :id => 78, :brand_id => 9, :name => 'Corsa', :tipo => 1},
                        { :id => 79, :brand_id => 9, :name => 'Corvette', :tipo => 1},
                        { :id => 80, :brand_id => 9, :name => 'Cutlass', :tipo => 1},
                        { :id => 81, :brand_id => 9, :name => 'Equinox', :tipo => 4},
                        { :id => 82, :brand_id => 9, :name => 'Express Van', :tipo => 4},
                        { :id => 83, :brand_id => 9, :name => 'HHR', :tipo => 4},
                        { :id => 84, :brand_id => 9, :name => 'Impala', :tipo => 1},
                        { :id => 85, :brand_id => 9, :name => 'Kodiak', :tipo => 16},
                        { :id => 86, :brand_id => 9, :name => 'Lumina', :tipo => 1},
                        { :id => 87, :brand_id => 9, :name => 'LUV', :tipo => 2},
                        { :id => 88, :brand_id => 9, :name => 'Malibu', :tipo => 1},
                        { :id => 89, :brand_id => 9, :name => 'Meriva', :tipo => 1},
                        { :id => 90, :brand_id => 9, :name => 'Montecarlo', :tipo => 1},
                        { :id => 91, :brand_id => 9, :name => 'Monza', :tipo => 1},
                        { :id => 92, :brand_id => 9, :name => 'Optra', :tipo => 1},
                        { :id => 93, :brand_id => 9, :name => 'S-10', :tipo => 6},
                        { :id => 94, :brand_id => 9, :name => 'Silhouette', :tipo => 4},
                        { :id => 95, :brand_id => 9, :name => 'Silverado', :tipo => 22},
                        { :id => 96, :brand_id => 9, :name => 'Sonora', :tipo => 4},
                        { :id => 97, :brand_id => 9, :name => 'Suburban', :tipo => 4},
                        { :id => 98, :brand_id => 9, :name => 'Tahoe', :tipo => 4},
                        { :id => 99, :brand_id => 9, :name => 'Tigra', :tipo => 1},
                        { :id => 100, :brand_id => 9, :name => 'Tornado', :tipo => 2},
                        { :id => 101, :brand_id => 9, :name => 'Tracker', :tipo => 4},
                        { :id => 102, :brand_id => 9, :name => 'Trailblazer', :tipo => 4},
                        { :id => 103, :brand_id => 9, :name => 'Uplander', :tipo => 4},
                        { :id => 104, :brand_id => 9, :name => 'Vectra', :tipo => 1},
                        { :id => 105, :brand_id => 9, :name => 'Venture', :tipo => 4},
                        { :id => 106, :brand_id => 9, :name => 'Yukon', :tipo => 4},
                        { :id => 107, :brand_id => 9, :name => 'Zafira', :tipo => 4},
                        { :id => 108, :brand_id => 10, :name => '300', :tipo => 1},
                        { :id => 109, :brand_id => 10, :name => 'Aspen', :tipo => 4},
                        { :id => 110, :brand_id => 10, :name => 'Caravan', :tipo => 4},
                        { :id => 111, :brand_id => 10, :name => 'Cirrus', :tipo => 1},
                        { :id => 112, :brand_id => 10, :name => 'Concorde', :tipo => 1},
                        { :id => 113, :brand_id => 10, :name => 'Crossfire', :tipo => 1},
                        { :id => 114, :brand_id => 10, :name => 'Dart', :tipo => 1},
                        { :id => 115, :brand_id => 10, :name => 'LeBaron', :tipo => 1},
                        { :id => 116, :brand_id => 10, :name => 'New Yorker', :tipo => 1},
                        { :id => 117, :brand_id => 10, :name => 'Pacifica', :tipo => 4},
                        { :id => 118, :brand_id => 10, :name => 'PT Cruiser', :tipo => 1},
                        { :id => 119, :brand_id => 10, :name => 'Sebring', :tipo => 1},
                        { :id => 120, :brand_id => 10, :name => 'Shadow', :tipo => 1},
                        { :id => 121, :brand_id => 10, :name => 'Spirit', :tipo => 1},
                        { :id => 122, :brand_id => 10, :name => 'Town & Country', :tipo => 4},
                        { :id => 123, :brand_id => 10, :name => 'Voyager', :tipo => 4},
                        { :id => 124, :brand_id => 11, :name => 'Atos', :tipo => 1},
                        { :id => 125, :brand_id => 11, :name => 'Attitude', :tipo => 1},
                        { :id => 126, :brand_id => 11, :name => 'Avenger', :tipo => 1},
                        { :id => 127, :brand_id => 11, :name => 'Caliber', :tipo => 1},
                        { :id => 128, :brand_id => 11, :name => 'Caravan', :tipo => 4},
                        { :id => 129, :brand_id => 11, :name => 'Challenger', :tipo => 1},
                        { :id => 130, :brand_id => 11, :name => 'Charger', :tipo => 1},
                        { :id => 131, :brand_id => 11, :name => 'Cirrus', :tipo => 1},
                        { :id => 132, :brand_id => 11, :name => 'Dakota', :tipo => 2},
                        { :id => 133, :brand_id => 11, :name => 'Durango', :tipo => 4},
                        { :id => 134, :brand_id => 11, :name => 'H100', :tipo => 16},
                        { :id => 135, :brand_id => 11, :name => 'Intrepid', :tipo => 1},
                        { :id => 136, :brand_id => 11, :name => 'Journey', :tipo => 4},
                        { :id => 137, :brand_id => 11, :name => 'Magnum', :tipo => 1},
                        { :id => 138, :brand_id => 11, :name => 'Neon', :tipo => 1},
                        { :id => 139, :brand_id => 11, :name => 'Nitro', :tipo => 4},
                        { :id => 140, :brand_id => 11, :name => 'Ram', :tipo => 18},
                        { :id => 141, :brand_id => 11, :name => 'Ramcharger', :tipo => 4},
                        { :id => 142, :brand_id => 11, :name => 'Sprinter', :tipo => 4},
                        { :id => 143, :brand_id => 11, :name => 'Stratus', :tipo => 1},
                        { :id => 144, :brand_id => 11, :name => 'Torton', :tipo => 16},
                        { :id => 145, :brand_id => 11, :name => 'Verna', :tipo => 1},
                        { :id => 146, :brand_id => 11, :name => 'Viper', :tipo => 1},
                        { :id => 147, :brand_id => 12, :name => '360', :tipo => 1},
                        { :id => 148, :brand_id => 12, :name => '550', :tipo => 1},
                        { :id => 149, :brand_id => 12, :name => '575M', :tipo => 1},
                        { :id => 150, :brand_id => 12, :name => '599 GTB Fiorano', :tipo => 1},
                        { :id => 151, :brand_id => 12, :name => '612 Scaglietti', :tipo => 1},
                        { :id => 152, :brand_id => 12, :name => 'California ', :tipo => 1},
                        { :id => 153, :brand_id => 12, :name => 'Enzo', :tipo => 1},
                        { :id => 154, :brand_id => 12, :name => 'F355', :tipo => 1},
                        { :id => 155, :brand_id => 12, :name => 'F40', :tipo => 1},
                        { :id => 156, :brand_id => 12, :name => 'F430', :tipo => 1},
                        { :id => 157, :brand_id => 12, :name => 'Testarossa', :tipo => 1},
                        { :id => 158, :brand_id => 13, :name => 'Aerostar', :tipo => 4},
                        { :id => 159, :brand_id => 13, :name => 'Bronco', :tipo => 6},
                        { :id => 160, :brand_id => 13, :name => 'Club Wagon', :tipo => 4},
                        { :id => 161, :brand_id => 13, :name => 'Contour', :tipo => 1},
                        { :id => 162, :brand_id => 13, :name => 'Cougar', :tipo => 1},
                        { :id => 163, :brand_id => 13, :name => 'Coupe', :tipo => 1},
                        { :id => 164, :brand_id => 13, :name => 'Courier', :tipo => 2},
                        { :id => 165, :brand_id => 13, :name => 'Crown Victoria', :tipo => 1},
                        { :id => 166, :brand_id => 13, :name => 'Econoline', :tipo => 4},
                        { :id => 167, :brand_id => 13, :name => 'EcoSport', :tipo => 4},
                        { :id => 168, :brand_id => 13, :name => 'Edge', :tipo => 4},
                        { :id => 169, :brand_id => 13, :name => 'Escape', :tipo => 4},
                        { :id => 170, :brand_id => 13, :name => 'Escort', :tipo => 1},
                        { :id => 171, :brand_id => 13, :name => 'Excursion', :tipo => 4},
                        { :id => 172, :brand_id => 13, :name => 'Expedition', :tipo => 4},
                        { :id => 173, :brand_id => 13, :name => 'Explorer', :tipo => 6},
                        { :id => 174, :brand_id => 13, :name => 'F-Serie', :tipo => 18},
                        { :id => 175, :brand_id => 13, :name => 'Falcon', :tipo => 1},
                        { :id => 176, :brand_id => 13, :name => 'Fiesta', :tipo => 1},
                        { :id => 177, :brand_id => 13, :name => 'Five Hundred', :tipo => 1},
                        { :id => 178, :brand_id => 13, :name => 'Focus', :tipo => 1},
                        { :id => 179, :brand_id => 13, :name => 'Freestar', :tipo => 4},
                        { :id => 180, :brand_id => 13, :name => 'Fusion', :tipo => 1},
                        { :id => 181, :brand_id => 13, :name => 'Ghia', :tipo => 1},
                        { :id => 182, :brand_id => 13, :name => 'Grand Marquis', :tipo => 1},
                        { :id => 183, :brand_id => 13, :name => 'Ikon', :tipo => 1},
                        { :id => 184, :brand_id => 13, :name => 'Ka', :tipo => 1},
                        { :id => 185, :brand_id => 13, :name => 'Lobo', :tipo => 2},
                        { :id => 186, :brand_id => 13, :name => 'LTD', :tipo => 1},
                        { :id => 187, :brand_id => 13, :name => 'Mondeo', :tipo => 1},
                        { :id => 188, :brand_id => 13, :name => 'Mustang', :tipo => 1},
                        { :id => 189, :brand_id => 13, :name => 'Mystique', :tipo => 1},
                        { :id => 190, :brand_id => 13, :name => 'Probe', :tipo => 1},
                        { :id => 191, :brand_id => 13, :name => 'Ranger', :tipo => 2},
                        { :id => 192, :brand_id => 13, :name => 'Sable', :tipo => 1},
                        { :id => 193, :brand_id => 13, :name => 'Taurus', :tipo => 1},
                        { :id => 194, :brand_id => 13, :name => 'Thunderbird', :tipo => 1},
                        { :id => 195, :brand_id => 13, :name => 'Topaz', :tipo => 1},
                        { :id => 196, :brand_id => 13, :name => 'Transit', :tipo => 4},
                        { :id => 197, :brand_id => 13, :name => 'Villager', :tipo => 4},
                        { :id => 198, :brand_id => 13, :name => 'Wagon', :tipo => 1},
                        { :id => 199, :brand_id => 13, :name => 'Windstar', :tipo => 4},
                        { :id => 200, :brand_id => 14, :name => 'Acadia', :tipo => 4},
                        { :id => 201, :brand_id => 14, :name => 'Astro', :tipo => 16},
                        { :id => 202, :brand_id => 14, :name => 'Brigadier', :tipo => 16},
                        { :id => 203, :brand_id => 14, :name => 'Canyon', :tipo => 2},
                        { :id => 204, :brand_id => 14, :name => 'Envoy', :tipo => 4},
                        { :id => 205, :brand_id => 14, :name => 'Jimmy', :tipo => 4},
                        { :id => 206, :brand_id => 14, :name => 'Safari', :tipo => 4},
                        { :id => 207, :brand_id => 14, :name => 'Savana', :tipo => 4},
                        { :id => 208, :brand_id => 14, :name => 'Sierra', :tipo => 18},
                        { :id => 209, :brand_id => 14, :name => 'Sonoma', :tipo => 2},
                        { :id => 210, :brand_id => 14, :name => 'Suburban', :tipo => 4},
                        { :id => 211, :brand_id => 14, :name => 'Topkick', :tipo => 16},
                        { :id => 212, :brand_id => 14, :name => 'Vandura', :tipo => 4},
                        { :id => 213, :brand_id => 14, :name => 'Yukon', :tipo => 4},
                        { :id => 214, :brand_id => 15, :name => 'Accord', :tipo => 1},
                        { :id => 215, :brand_id => 15, :name => 'Civic', :tipo => 1},
                        { :id => 216, :brand_id => 15, :name => 'CR-V', :tipo => 4},
                        { :id => 217, :brand_id => 15, :name => 'Element', :tipo => 4},
                        { :id => 218, :brand_id => 15, :name => 'Fit', :tipo => 1},
                        { :id => 219, :brand_id => 15, :name => 'Odyssey', :tipo => 4},
                        { :id => 220, :brand_id => 15, :name => 'Passport', :tipo => 4},
                        { :id => 221, :brand_id => 15, :name => 'Pilot', :tipo => 4},
                        { :id => 222, :brand_id => 15, :name => 'Ridgeline', :tipo => 2},
                        { :id => 223, :brand_id => 16, :name => 'H1', :tipo => 4},
                        { :id => 224, :brand_id => 16, :name => 'H2', :tipo => 6},
                        { :id => 225, :brand_id => 16, :name => 'H3', :tipo => 6},
                        { :id => 226, :brand_id => 17, :name => 'Elantra', :tipo => 1},
                        { :id => 227, :brand_id => 17, :name => 'Excel', :tipo => 1},
                        { :id => 228, :brand_id => 17, :name => 'H-1', :tipo => 4},
                        { :id => 229, :brand_id => 17, :name => 'Matrix', :tipo => 2},
                        { :id => 230, :brand_id => 17, :name => 'Santa Fe', :tipo => 4},
                        { :id => 231, :brand_id => 17, :name => 'Sonata', :tipo => 1},
                        { :id => 232, :brand_id => 17, :name => 'Tucson', :tipo => 4},
                        { :id => 233, :brand_id => 17, :name => 'Veracruz', :tipo => 4},
                        { :id => 234, :brand_id => 18, :name => 'I30', :tipo => 1},
                        { :id => 235, :brand_id => 18, :name => 'Q30', :tipo => 1},
                        { :id => 236, :brand_id => 18, :name => 'Q45', :tipo => 1},
                        { :id => 237, :brand_id => 19, :name => 'Serie 3000', :tipo => 16},
                        { :id => 238, :brand_id => 19, :name => 'Serie 4000', :tipo => 16},
                        { :id => 239, :brand_id => 19, :name => 'Serie 5000', :tipo => 16},
                        { :id => 240, :brand_id => 19, :name => 'Serie 7000', :tipo => 16},
                        { :id => 241, :brand_id => 19, :name => 'Serie 9000', :tipo => 16},
                        { :id => 242, :brand_id => 20, :name => 'Amigo', :tipo => 6},
                        { :id => 243, :brand_id => 20, :name => 'Ascender', :tipo => 4},
                        { :id => 244, :brand_id => 20, :name => 'Axiom', :tipo => 4},
                        { :id => 245, :brand_id => 20, :name => 'ELF', :tipo => 16},
                        { :id => 246, :brand_id => 20, :name => 'Pickup', :tipo => 2},
                        { :id => 247, :brand_id => 20, :name => 'Rodeo', :tipo => 4},
                        { :id => 248, :brand_id => 20, :name => 'Trooper', :tipo => 4},
                        { :id => 249, :brand_id => 21, :name => 'S-Type', :tipo => 1},
                        { :id => 250, :brand_id => 21, :name => 'X-Type', :tipo => 1},
                        { :id => 251, :brand_id => 21, :name => 'XJ', :tipo => 1},
                        { :id => 252, :brand_id => 21, :name => 'XK', :tipo => 1},
                        { :id => 253, :brand_id => 22, :name => 'Cherokee', :tipo => 4},
                        { :id => 254, :brand_id => 22, :name => 'CJ', :tipo => 4},
                        { :id => 255, :brand_id => 22, :name => 'Commander', :tipo => 4},
                        { :id => 256, :brand_id => 22, :name => 'Compass', :tipo => 4},
                        { :id => 257, :brand_id => 22, :name => 'Grand Cherokee', :tipo => 4},
                        { :id => 258, :brand_id => 22, :name => 'Liberty', :tipo => 4},
                        { :id => 259, :brand_id => 22, :name => 'Patriot', :tipo => 4},
                        { :id => 261, :brand_id => 22, :name => 'Sahara', :tipo => 4},
                        { :id => 262, :brand_id => 22, :name => 'Wagoneer', :tipo => 4},
                        { :id => 263, :brand_id => 22, :name => 'Willlys', :tipo => 4},
                        { :id => 264, :brand_id => 22, :name => 'Wrangler', :tipo => 4},
                        { :id => 265, :brand_id => 23, :name => 'C500', :tipo => 16},
                        { :id => 266, :brand_id => 23, :name => 'T2000', :tipo => 16},
                        { :id => 267, :brand_id => 23, :name => 'T300', :tipo => 16},
                        { :id => 268, :brand_id => 23, :name => 'T600', :tipo => 16},
                        { :id => 269, :brand_id => 23, :name => 'T604', :tipo => 16},
                        { :id => 270, :brand_id => 23, :name => 'T800', :tipo => 16},
                        { :id => 271, :brand_id => 23, :name => 'W900', :tipo => 16},
                        { :id => 272, :brand_id => 25, :name => 'Countach', :tipo => 1},
                        { :id => 273, :brand_id => 25, :name => 'Diablo', :tipo => 1},
                        { :id => 274, :brand_id => 25, :name => 'Gallardo', :tipo => 1},
                        { :id => 275, :brand_id => 25, :name => 'Murciélago', :tipo => 1},
                        { :id => 276, :brand_id => 25, :name => 'Reventón', :tipo => 1},
                        { :id => 277, :brand_id => 26, :name => 'Discovery', :tipo => 4},
                        { :id => 278, :brand_id => 26, :name => 'Free Lander', :tipo => 4},
                        { :id => 279, :brand_id => 26, :name => 'LR2', :tipo => 4},
                        { :id => 280, :brand_id => 26, :name => 'LR3', :tipo => 4},
                        { :id => 281, :brand_id => 26, :name => 'Range Rover', :tipo => 4},
                        { :id => 282, :brand_id => 27, :name => 'Aviator', :tipo => 4},
                        { :id => 283, :brand_id => 27, :name => 'Black Wood', :tipo => 2},
                        { :id => 284, :brand_id => 27, :name => 'Cartier', :tipo => 1},
                        { :id => 285, :brand_id => 27, :name => 'Continental', :tipo => 1},
                        { :id => 286, :brand_id => 27, :name => 'LS', :tipo => 1},
                        { :id => 287, :brand_id => 27, :name => 'Mark LT', :tipo => 2},
                        { :id => 288, :brand_id => 27, :name => 'Mark VIII', :tipo => 1},
                        { :id => 289, :brand_id => 27, :name => 'MKS', :tipo => 1},
                        { :id => 290, :brand_id => 27, :name => 'MKX', :tipo => 4},
                        { :id => 291, :brand_id => 27, :name => 'MKZ', :tipo => 1},
                        { :id => 292, :brand_id => 27, :name => 'Navigator', :tipo => 4},
                        { :id => 293, :brand_id => 27, :name => 'Town Car', :tipo => 1},
                        { :id => 294, :brand_id => 27, :name => 'Zephyr', :tipo => 1},
                        { :id => 295, :brand_id => 28, :name => 'Elise', :tipo => 1},
                        { :id => 296, :brand_id => 29, :name => 'Coupé', :tipo => 1},
                        { :id => 297, :brand_id => 29, :name => 'GranSport', :tipo => 1},
                        { :id => 298, :brand_id => 29, :name => 'GranTurismo', :tipo => 1},
                        { :id => 299, :brand_id => 29, :name => 'Quattroporte', :tipo => 1},
                        { :id => 300, :brand_id => 29, :name => 'Spyder', :tipo => 1},
                        { :id => 301, :brand_id => 30, :name => '57', :tipo => 1},
                        { :id => 302, :brand_id => 30, :name => '62', :tipo => 1},
                        { :id => 303, :brand_id => 31, :name => '3', :tipo => 1},
                        { :id => 304, :brand_id => 31, :name => '5', :tipo => 4},
                        { :id => 305, :brand_id => 31, :name => '6', :tipo => 1},
                        { :id => 306, :brand_id => 31, :name => '626', :tipo => 1},
                        { :id => 307, :brand_id => 31, :name => 'CX-7', :tipo => 4},
                        { :id => 308, :brand_id => 31, :name => 'CX-9', :tipo => 4},
                        { :id => 309, :brand_id => 31, :name => 'Mpv', :tipo => 4},
                        { :id => 310, :brand_id => 31, :name => 'MX-5', :tipo => 1},
                        { :id => 311, :brand_id => 31, :name => 'Serie B', :tipo => 2},
                        { :id => 312, :brand_id => 31, :name => 'Tribute', :tipo => 4},
                        { :id => 313, :brand_id => 32, :name => 'Allegro', :tipo => 16},
                        { :id => 314, :brand_id => 32, :name => 'Andare', :tipo => 16},
                        { :id => 315, :brand_id => 32, :name => 'Antiguos', :tipo => 1},
                        { :id => 316, :brand_id => 32, :name => 'Boxer', :tipo => 16},
                        { :id => 317, :brand_id => 32, :name => 'Clase A', :tipo => 1},
                        { :id => 318, :brand_id => 32, :name => 'Clase B', :tipo => 1},
                        { :id => 319, :brand_id => 32, :name => 'Clase C', :tipo => 1},
                        { :id => 320, :brand_id => 32, :name => 'Clase CL', :tipo => 1},
                        { :id => 321, :brand_id => 32, :name => 'Clase CLK', :tipo => 1},
                        { :id => 322, :brand_id => 32, :name => 'Clase CLS', :tipo => 1},
                        { :id => 323, :brand_id => 32, :name => 'Clase E', :tipo => 1},
                        { :id => 324, :brand_id => 32, :name => 'Clase G', :tipo => 4},
                        { :id => 325, :brand_id => 32, :name => 'Clase GL', :tipo => 4},
                        { :id => 326, :brand_id => 32, :name => 'Clase GLK', :tipo => 4},
                        { :id => 327, :brand_id => 32, :name => 'Clase M', :tipo => 4},
                        { :id => 328, :brand_id => 32, :name => 'Clase ML', :tipo => 4},
                        { :id => 329, :brand_id => 32, :name => 'Clase R', :tipo => 4},
                        { :id => 330, :brand_id => 32, :name => 'Clase S', :tipo => 1},
                        { :id => 331, :brand_id => 32, :name => 'Clase SL', :tipo => 1},
                        { :id => 332, :brand_id => 32, :name => 'Clase SLK', :tipo => 1},
                        { :id => 333, :brand_id => 32, :name => 'Midibús', :tipo => 16},
                        { :id => 334, :brand_id => 32, :name => 'Multego', :tipo => 16},
                        { :id => 335, :brand_id => 32, :name => 'Setra', :tipo => 16},
                        { :id => 336, :brand_id => 32, :name => 'SLR', :tipo => 1},
                        { :id => 337, :brand_id => 32, :name => 'Torino', :tipo => 16},
                        { :id => 338, :brand_id => 32, :name => 'Turiclass', :tipo => 16},
                        { :id => 339, :brand_id => 32, :name => 'Sprinter', :tipo => 4},
                        { :id => 340, :brand_id => 33, :name => 'Cougar', :tipo => 1},
                        { :id => 341, :brand_id => 33, :name => 'Grand Marquis', :tipo => 1},
                        { :id => 342, :brand_id => 33, :name => 'Mariner', :tipo => 4},
                        { :id => 343, :brand_id => 33, :name => 'Milan', :tipo => 1},
                        { :id => 344, :brand_id => 33, :name => 'Montego', :tipo => 1},
                        { :id => 345, :brand_id => 33, :name => 'Mountaineer', :tipo => 4},
                        { :id => 346, :brand_id => 33, :name => 'Mystique', :tipo => 1},
                        { :id => 347, :brand_id => 33, :name => 'Sable', :tipo => 1},
                        { :id => 348, :brand_id => 33, :name => 'Villager', :tipo => 4},
                        { :id => 349, :brand_id => 34, :name => 'A', :tipo => 1},
                        { :id => 350, :brand_id => 34, :name => 'Midget', :tipo => 1},
                        { :id => 351, :brand_id => 34, :name => 'TF', :tipo => 1},
                        { :id => 352, :brand_id => 34, :name => 'ZR', :tipo => 1},
                        { :id => 353, :brand_id => 34, :name => 'ZT', :tipo => 1},
                        { :id => 354, :brand_id => 35, :name => 'Cooper', :tipo => 1},
                        { :id => 355, :brand_id => 36, :name => 'Eclipse', :tipo => 1},
                        { :id => 356, :brand_id => 36, :name => 'Endeavor', :tipo => 4},
                        { :id => 357, :brand_id => 36, :name => 'Galant', :tipo => 1},
                        { :id => 358, :brand_id => 36, :name => 'Grandis', :tipo => 4},
                        { :id => 359, :brand_id => 36, :name => 'L200', :tipo => 2},
                        { :id => 360, :brand_id => 36, :name => 'Lancer', :tipo => 1},
                        { :id => 361, :brand_id => 36, :name => 'Montero', :tipo => 4},
                        { :id => 362, :brand_id => 36, :name => 'Outlander', :tipo => 4},
                        { :id => 363, :brand_id => 36, :name => 'Space Star', :tipo => 4},
                        { :id => 364, :brand_id => 37, :name => '300ZX', :tipo => 1},
                        { :id => 365, :brand_id => 37, :name => '350Z', :tipo => 1},
                        { :id => 366, :brand_id => 37, :name => 'Almera', :tipo => 1},
                        { :id => 367, :brand_id => 37, :name => 'Altima', :tipo => 1},
                        { :id => 368, :brand_id => 37, :name => 'Aprio', :tipo => 1},
                        { :id => 369, :brand_id => 37, :name => 'Armada', :tipo => 4},
                        { :id => 370, :brand_id => 37, :name => 'Cabstar', :tipo => 16},
                        { :id => 371, :brand_id => 37, :name => 'Datsun', :tipo => 1},
                        { :id => 372, :brand_id => 37, :name => 'Estaquitas', :tipo => 2},
                        { :id => 373, :brand_id => 37, :name => 'Frontier', :tipo => 2},
                        { :id => 374, :brand_id => 37, :name => 'Hikari', :tipo => 1},
                        { :id => 375, :brand_id => 37, :name => 'Ichi Van', :tipo => 4},
                        { :id => 376, :brand_id => 37, :name => 'Lucino', :tipo => 1},
                        { :id => 377, :brand_id => 37, :name => 'Maxima', :tipo => 1},
                        { :id => 378, :brand_id => 37, :name => 'Micra', :tipo => 1},
                        { :id => 379, :brand_id => 37, :name => 'Murano', :tipo => 4},
                        { :id => 380, :brand_id => 37, :name => 'Pathfinder', :tipo => 4},
                        { :id => 381, :brand_id => 37, :name => 'Platina', :tipo => 1},
                        { :id => 382, :brand_id => 37, :name => 'Quest', :tipo => 4},
                        { :id => 383, :brand_id => 37, :name => 'Rogue', :tipo => 4},
                        { :id => 384, :brand_id => 37, :name => 'Sentra', :tipo => 1},
                        { :id => 385, :brand_id => 37, :name => 'SX', :tipo => 1},
                        { :id => 386, :brand_id => 37, :name => 'Tiida', :tipo => 1},
                        { :id => 387, :brand_id => 37, :name => 'Titan', :tipo => 2},
                        { :id => 388, :brand_id => 37, :name => 'Tsubame', :tipo => 1},
                        { :id => 389, :brand_id => 37, :name => 'Tsuru', :tipo => 1},
                        { :id => 390, :brand_id => 37, :name => 'Urvan', :tipo => 4},
                        { :id => 391, :brand_id => 37, :name => 'X-Terra', :tipo => 4},
                        { :id => 392, :brand_id => 37, :name => 'X-Trail', :tipo => 4},
                        { :id => 393, :brand_id => 38, :name => '206', :tipo => 1},
                        { :id => 394, :brand_id => 38, :name => '306', :tipo => 1},
                        { :id => 395, :brand_id => 38, :name => '307', :tipo => 1},
                        { :id => 396, :brand_id => 38, :name => '405', :tipo => 1},
                        { :id => 397, :brand_id => 38, :name => '406', :tipo => 1},
                        { :id => 398, :brand_id => 38, :name => '407', :tipo => 1},
                        { :id => 399, :brand_id => 38, :name => '607', :tipo => 1},
                        { :id => 400, :brand_id => 38, :name => 'Grand Raid', :tipo => 4},
                        { :id => 401, :brand_id => 38, :name => 'Partner', :tipo => 4},
                        { :id => 402, :brand_id => 39, :name => 'Barracuda', :tipo => 1},
                        { :id => 403, :brand_id => 39, :name => 'Breeze', :tipo => 1},
                        { :id => 404, :brand_id => 39, :name => 'Neon', :tipo => 1},
                        { :id => 405, :brand_id => 39, :name => 'Road Runner', :tipo => 1},
                        { :id => 406, :brand_id => 39, :name => 'Voyager', :tipo => 4},
                        { :id => 407, :brand_id => 40, :name => 'Aztek', :tipo => 4},
                        { :id => 408, :brand_id => 40, :name => 'Bonneville', :tipo => 1},
                        { :id => 409, :brand_id => 40, :name => 'Firebird', :tipo => 1},
                        { :id => 410, :brand_id => 40, :name => 'G3', :tipo => 1},
                        { :id => 411, :brand_id => 40, :name => 'G4', :tipo => 1},
                        { :id => 412, :brand_id => 40, :name => 'G5', :tipo => 1},
                        { :id => 413, :brand_id => 40, :name => 'G6', :tipo => 1},
                        { :id => 414, :brand_id => 40, :name => 'Grand Am', :tipo => 1},
                        { :id => 415, :brand_id => 40, :name => 'Grand Prix', :tipo => 1},
                        { :id => 416, :brand_id => 40, :name => 'Matiz', :tipo => 1},
                        { :id => 417, :brand_id => 40, :name => 'Montana', :tipo => 4},
                        { :id => 418, :brand_id => 40, :name => 'Solstice', :tipo => 1},
                        { :id => 419, :brand_id => 40, :name => 'Sunfire', :tipo => 1},
                        { :id => 420, :brand_id => 40, :name => 'Torrent', :tipo => 4},
                        { :id => 421, :brand_id => 40, :name => 'Trans Am', :tipo => 1},
                        { :id => 422, :brand_id => 40, :name => 'Trans Sport', :tipo => 4},
                        { :id => 423, :brand_id => 41, :name => '911', :tipo => 1},
                        { :id => 424, :brand_id => 41, :name => 'Boxster', :tipo => 1},
                        { :id => 425, :brand_id => 41, :name => 'Cayenne', :tipo => 4},
                        { :id => 426, :brand_id => 41, :name => 'Cayman', :tipo => 1},
                        { :id => 427, :brand_id => 42, :name => 'Ambassador', :tipo => 1},
                        { :id => 428, :brand_id => 42, :name => 'AMX', :tipo => 1},
                        { :id => 429, :brand_id => 42, :name => 'Gremlin', :tipo => 1},
                        { :id => 430, :brand_id => 42, :name => 'Javelin', :tipo => 1},
                        { :id => 431, :brand_id => 42, :name => 'Rambler', :tipo => 1},
                        { :id => 432, :brand_id => 43, :name => 'Clio', :tipo => 1},
                        { :id => 433, :brand_id => 43, :name => 'Kangoo', :tipo => 4},
                        { :id => 434, :brand_id => 43, :name => 'Koleos', :tipo => 4},
                        { :id => 435, :brand_id => 43, :name => 'Laguna', :tipo => 1},
                        { :id => 436, :brand_id => 43, :name => 'Megane', :tipo => 1},
                        { :id => 437, :brand_id => 43, :name => 'Scenic', :tipo => 4},
                        { :id => 438, :brand_id => 43, :name => 'Trafic', :tipo => 4},
                        { :id => 439, :brand_id => 44, :name => 'Phantom', :tipo => 1},
                        { :id => 440, :brand_id => 44, :name => 'Silver Shadow', :tipo => 1},
                        { :id => 441, :brand_id => 45, :name => '75', :tipo => 1},
                        { :id => 442, :brand_id => 46, :name => '9-3', :tipo => 1},
                        { :id => 443, :brand_id => 46, :name => '9-5', :tipo => 1},
                        { :id => 444, :brand_id => 47, :name => 'Asta', :tipo => 1},
                        { :id => 445, :brand_id => 47, :name => 'Aura', :tipo => 1},
                        { :id => 446, :brand_id => 47, :name => 'SC1', :tipo => 1},
                        { :id => 447, :brand_id => 47, :name => 'SC2', :tipo => 1},
                        { :id => 448, :brand_id => 47, :name => 'SL2', :tipo => 1},
                        { :id => 449, :brand_id => 48, :name => 'Alhambra', :tipo => 4},
                        { :id => 450, :brand_id => 48, :name => 'Altea', :tipo => 1},
                        { :id => 451, :brand_id => 48, :name => 'Cordoba', :tipo => 1},
                        { :id => 452, :brand_id => 48, :name => 'Ibiza', :tipo => 1},
                        { :id => 453, :brand_id => 48, :name => 'Leon', :tipo => 1},
                        { :id => 454, :brand_id => 48, :name => 'Toledo', :tipo => 1},
                        { :id => 455, :brand_id => 49, :name => 'Forfour', :tipo => 1},
                        { :id => 456, :brand_id => 49, :name => 'Fortwo', :tipo => 1},
                        { :id => 457, :brand_id => 49, :name => 'Roadster', :tipo => 1},
                        { :id => 458, :brand_id => 49, :name => 'Smart', :tipo => 1},
                        { :id => 459, :brand_id => 50, :name => 'Forester', :tipo => 4},
                        { :id => 460, :brand_id => 50, :name => 'Impreza', :tipo => 1},
                        { :id => 461, :brand_id => 50, :name => 'Legacy', :tipo => 1},
                        { :id => 462, :brand_id => 50, :name => 'Outback', :tipo => 1},
                        { :id => 463, :brand_id => 50, :name => 'Tribeca', :tipo => 4},
                        { :id => 464, :brand_id => 51, :name => 'Aerio', :tipo => 1},
                        { :id => 465, :brand_id => 51, :name => 'Esteem', :tipo => 1},
                        { :id => 466, :brand_id => 51, :name => 'Grand Vitara', :tipo => 4},
                        { :id => 467, :brand_id => 51, :name => 'Sidekick', :tipo => 4},
                        { :id => 468, :brand_id => 51, :name => 'Swift', :tipo => 1},
                        { :id => 469, :brand_id => 51, :name => 'SX4', :tipo => 1},
                        { :id => 470, :brand_id => 51, :name => 'XL7', :tipo => 4},
                        { :id => 471, :brand_id => 52, :name => '4Runner', :tipo => 4},
                        { :id => 472, :brand_id => 52, :name => 'Avalon', :tipo => 1},
                        { :id => 473, :brand_id => 52, :name => 'Avanza', :tipo => 1},
                        { :id => 474, :brand_id => 52, :name => 'Camry', :tipo => 1},
                        { :id => 475, :brand_id => 52, :name => 'Corolla', :tipo => 1},
                        { :id => 476, :brand_id => 52, :name => 'FJ Cruiser', :tipo => 4},
                        { :id => 477, :brand_id => 52, :name => 'Hiace', :tipo => 4},
                        { :id => 478, :brand_id => 52, :name => 'Highlander', :tipo => 4},
                        { :id => 479, :brand_id => 52, :name => 'Hilux', :tipo => 2},
                        { :id => 480, :brand_id => 52, :name => 'Land Cruiser', :tipo => 4},
                        { :id => 481, :brand_id => 52, :name => 'Matrix', :tipo => 1},
                        { :id => 482, :brand_id => 52, :name => 'MR2', :tipo => 1},
                        { :id => 483, :brand_id => 52, :name => 'Pickup', :tipo => 2},
                        { :id => 484, :brand_id => 52, :name => 'RAV4', :tipo => 4},
                        { :id => 485, :brand_id => 52, :name => 'Sequoia', :tipo => 4},
                        { :id => 486, :brand_id => 52, :name => 'Sienna', :tipo => 4},
                        { :id => 487, :brand_id => 52, :name => 'Solara', :tipo => 1},
                        { :id => 488, :brand_id => 52, :name => 'T100', :tipo => 2},
                        { :id => 489, :brand_id => 52, :name => 'Tacoma', :tipo => 2},
                        { :id => 490, :brand_id => 52, :name => 'Tundra', :tipo => 2},
                        { :id => 491, :brand_id => 52, :name => 'Yaris', :tipo => 1},
                        { :id => 493, :brand_id => 53, :name => 'Beetle', :tipo => 1},
                        { :id => 494, :brand_id => 53, :name => 'Bora', :tipo => 1},
                        { :id => 496, :brand_id => 53, :name => 'Combi', :tipo => 4},
                        { :id => 498, :brand_id => 53, :name => 'Crafter', :tipo => 20},
                        { :id => 499, :brand_id => 53, :name => 'CrossFox', :tipo => 4},
                        { :id => 500, :brand_id => 53, :name => 'Derby', :tipo => 1},
                        { :id => 501, :brand_id => 53, :name => 'Eurovan', :tipo => 4},
                        { :id => 503, :brand_id => 53, :name => 'Golf', :tipo => 1},
                        { :id => 505, :brand_id => 53, :name => 'Jetta', :tipo => 1},
                        { :id => 506, :brand_id => 53, :name => 'Línea Volkbus', :tipo => 16},
                        { :id => 507, :brand_id => 53, :name => 'Línea Worker', :tipo => 16},
                        { :id => 508, :brand_id => 53, :name => 'Lupo', :tipo => 1},
                        { :id => 509, :brand_id => 53, :name => 'Passat', :tipo => 1},
                        { :id => 510, :brand_id => 53, :name => 'Pick Up', :tipo => 2},
                        { :id => 511, :brand_id => 53, :name => 'Pointer', :tipo => 3},
                        { :id => 512, :brand_id => 53, :name => 'Polo', :tipo => 1},
                        { :id => 513, :brand_id => 53, :name => 'Safari', :tipo => 4},
                        { :id => 514, :brand_id => 53, :name => 'Sedan', :tipo => 1},
                        { :id => 515, :brand_id => 53, :name => 'Sharan', :tipo => 4},
                        { :id => 516, :brand_id => 53, :name => 'SportVan', :tipo => 4},
                        { :id => 517, :brand_id => 53, :name => 'Touareg', :tipo => 4},
                        { :id => 518, :brand_id => 53, :name => 'Van', :tipo => 4},
                        { :id => 519, :brand_id => 54, :name => 'C30', :tipo => 1},
                        { :id => 520, :brand_id => 54, :name => 'C70', :tipo => 1},
                        { :id => 521, :brand_id => 54, :name => 'S40', :tipo => 1},
                        { :id => 522, :brand_id => 54, :name => 'S60', :tipo => 1},
                        { :id => 523, :brand_id => 54, :name => 'S80', :tipo => 1},
                        { :id => 524, :brand_id => 54, :name => 'V70', :tipo => 1},
                        { :id => 525, :brand_id => 54, :name => 'XC90', :tipo => 4},
                        { :id => 526, :brand_id => 55, :name => 'Irizar', :tipo => 16},
                        { :id => 527, :brand_id => 55, :name => 'K 270', :tipo => 16},
                        { :id => 528, :brand_id => 55, :name => 'K 310', :tipo => 16},
                        { :id => 529, :brand_id => 55, :name => 'K270', :tipo => 16},
                        { :id => 530, :brand_id => 55, :name => 'K310', :tipo => 16},
                        { :id => 531, :brand_id => 55, :name => 'K380', :tipo => 16},
                        { :id => 532, :brand_id => 55, :name => 'K420', :tipo => 16},
                        { :id => 533, :brand_id => 55, :name => 'P 420', :tipo => 16},
                        { :id => 534, :brand_id => 55, :name => 'R 420', :tipo => 16},
                        { :id => 535, :brand_id => 55, :name => 'R 480', :tipo => 16},
                        { :id => 536, :brand_id => 55, :name => 'R480', :tipo => 16},
                        { :id => 537, :brand_id => 69, :name => 'Cascadia', :tipo => 16},
                        { :id => 538, :brand_id => 69, :name => 'Century', :tipo => 16},
                        { :id => 539, :brand_id => 69, :name => 'Columbia', :tipo => 16},
                        { :id => 540, :brand_id => 69, :name => 'Condor', :tipo => 16},
                        { :id => 541, :brand_id => 69, :name => 'Coronado', :tipo => 16},
                        { :id => 542, :brand_id => 69, :name => 'FLD', :tipo => 16},
                        { :id => 543, :brand_id => 69, :name => 'M2', :tipo => 16},
                        { :id => 544, :brand_id => 69, :name => 'Sprinter', :tipo => 16},
                        { :id => 545, :brand_id => 40, :name => 'Fiero', :tipo => 1},
                        { :id => 547, :brand_id => 22, :name => 'Comanche', :tipo => 2},
                        { :id => 548, :brand_id => 13, :name => 'Galaxie', :tipo => 1},
                        { :id => 549, :brand_id => 13, :name => 'Fairlane', :tipo => 1},
                        { :id => 550, :brand_id => 13, :name => 'Maverick', :tipo => 1},
                        { :id => 551, :brand_id => 8, :name => 'Fleetwood', :tipo => 1},
                        { :id => 552, :brand_id => 7, :name => 'Skylark', :tipo => 1},
                        { :id => 553, :brand_id => 10, :name => 'Phantom', :tipo => 1},
                        { :id => 554, :brand_id => 11, :name => 'Valiant', :tipo => 1},
                        { :id => 555, :brand_id => 36, :name => 'Mirage', :tipo => 1},
                        { :id => 556, :brand_id => 37, :name => 'Pickup', :tipo => 2},
                        { :id => 557, :brand_id => 9, :name => 'Van', :tipo => 4},
                        { :id => 558, :brand_id => 11, :name => 'Ram Van', :tipo => 4},
                        { :id => 559, :brand_id => 72, :name => '500', :tipo => 1},
                        { :id => 560, :brand_id => 72, :name => 'Albea', :tipo => 1},
                        { :id => 561, :brand_id => 72, :name => 'Ducato', :tipo => 16},
                        { :id => 562, :brand_id => 72, :name => 'Grande Punto', :tipo => 1},
                        { :id => 563, :brand_id => 72, :name => 'Idea', :tipo => 4},
                        { :id => 564, :brand_id => 72, :name => 'Palio', :tipo => 4},
                        { :id => 565, :brand_id => 72, :name => 'Panda', :tipo => 1},
                        { :id => 566, :brand_id => 72, :name => 'Stilo Schumacher', :tipo => 1},
                        { :id => 567, :brand_id => 72, :name => 'Strada', :tipo => 2},
                        { :id => 568, :brand_id => 73, :name => 'Alero', :tipo => 1},
                        { :id => 569, :brand_id => 73, :name => 'Bravada', :tipo => 4},
                        { :id => 570, :brand_id => 73, :name => 'Cutlass', :tipo => 1},
                        { :id => 571, :brand_id => 73, :name => 'Tornado', :tipo => 1},
                        { :id => 572, :brand_id => 53, :name => 'Caribe', :tipo => 1},
                        { :id => 573, :brand_id => 54, :name => 'V40', :tipo => 1},
                        { :id => 574, :brand_id => 73, :name => 'Silhouette', :tipo => 4},
                        { :id => 575, :brand_id => 74, :name => 'HTQ', :tipo => 16},
                        { :id => 576, :brand_id => 21, :name => 'XF', :tipo => 1},
                        { :id => 577, :brand_id => 53, :name => 'Cabrio', :tipo => 1},
                        { :id => 578, :brand_id => 53, :name => 'Atlantic', :tipo => 1},
                        { :id => 579, :brand_id => 54, :name => 'XC60', :tipo => 4},
                        { :id => 580, :brand_id => 72, :name => 'Palio', :tipo => 1},
                        { :id => 581, :brand_id => 38, :name => '207', :tipo => 1},
                        { :id => 582, :brand_id => 38, :name => '308', :tipo => 1},
                        { :id => 583, :brand_id => 8, :name => 'Allanté', :tipo => 1},
                        { :id => 584, :brand_id => 9, :name => 'El Camino', :tipo => 1},
                        { :id => 585, :brand_id => 10, :name => 'Valiant', :tipo => 1},
                        { :id => 586, :brand_id => 11, :name => 'Dart', :tipo => 1},
                        { :id => 587, :brand_id => 13, :name => 'Fairmont', :tipo => 1},
                        { :id => 588, :brand_id => 17, :name => 'Verna', :tipo => 1},
                        { :id => 589, :brand_id => 43, :name => 'Encore', :tipo => 1},
                        { :id => 590, :brand_id => 43, :name => 'Alliance', :tipo => 1},
                        { :id => 591, :brand_id => 52, :name => 'Celica', :tipo => 1},
                        { :id => 592, :brand_id => 53, :name => 'Gol', :tipo => 1},
                        { :id => 593, :brand_id => 53, :name => 'Safari', :tipo => 1},
                        { :id => 594, :brand_id => 9, :name => 'Cruze', :tipo => 1},
                        { :id => 595, :brand_id => 9, :name => 'Traverse', :tipo => 4},
                        { :id => 596, :brand_id => 15, :name => 'City', :tipo => 1},
                        { :id => 597, :brand_id => 53, :name => 'Tiguan', :tipo => 4},
                        { :id => 598, :brand_id => 47, :name => 'VUE', :tipo => 4},
                        { :id => 599, :brand_id => 47, :name => 'Outlook', :tipo => 4},
                        { :id => 600, :brand_id => 9, :name => 'Spark', :tipo => 1},
                        { :id => 601, :brand_id => 9, :name => 'Matiz', :tipo => 1},
                        { :id => 602, :brand_id => 37, :name => 'Versa', :tipo => 1}
                       ])
